### ISSUE TITLE
OHQ styling applied to WP backend

### ISSUE THREAD

**Issue by mmarquiscreative** [mmarquiscreative/agx-OHQ-member-noForms#1]
**seems to affect:**
• h1
• h2
• <a> tags (buttons) — (for example class = button button-primary button-hero load-customize hide-if-no-customize)

**Potential causes:**
Might be from global styles in the OHQ style sheet
Might be from styles given the !important declaration in the style sheet
Potentially some bug with the back-end settings for the plugin

**Comment by mmarquiscreative** [comment]
![Screen Shot 2020-01-21 at 4 45 52 PM](https://user-images.githubusercontent.com/28794003/72925352-66facf80-3d07-11ea-98b0-fc07ee9aacd4.png)

Located in post editing page

**Comment by see8ch** [comment]
Fixed in new repo - commit 3f630bdabc766f3056506e46d6be8034bea4a274
